### ISSUE TITLE
Discovery research - Switch between intakes

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#142]
This card is about discovering stakeholders' perspectives on the switch between intakes.

### Questions
- [ ] Does NWBC expect applicants to see both intakes in one UI?
- [ ] Should applicants be able to see the intake # for their applications?
- [ ] When an application from an early intake is told to revise & resubmit to a later intake, what's the process?

### Tasks
- [ ] Meet with Howard in 4pm meetings
- [ ] Create journey map for each user or business flow diagram
- [ ] Identify pain points
- [ ] Ideate solutions
- [ ] Validate with NWBC
- [ ] Ideally, validate with applicants as well
