### ISSUE TITLE
Design mapping/GIS Data Process

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#159]
The data team's process is decently defined and we need to design a system that reduces their frictions while meeting NWBC & CITZ's needs.

### Questions
- [x] How will NWBC use mapping data?
- [ ] Does NWBC expect data team to do something with the extra maps?

### Tasks
- [x] Refine [Journey Map](https://miro.com/app/board/uXjVORZW4n4=/?moveToWidget=3458764520043523940&cot=14) of data team's process
- [x] Define pain points & constraints
- [x] Design different solutions
- [x] Get dev team's perspective
- [x] Present findings to NWBC & CITZ
- [ ] Create cards in Zenhub for development

**Comment by elliottSlee** [comment]
Met with Rachel, Harpreet, Krista, & Stephen on June 6th.
[12:18 p.m.] Elliott Lee (Guest)
    Yesterday's meeting was great. Would everyone mind validating the conclusions I drew?

1. We will collect 3 maps:
- Eligibility mapping tool output
- Current Network Infrastructure with the following layers:
     - All applicant-owned or operated fibre lines within British Columbia. Fibre data must show long-haul, regional and core community lines; applicants do not need to show fibre drops to the premise
     - All applicant-owned or operated PoPs, COs, towers, and microwave links within British Columbia
     - Current coverage for the communities proposed in the project; identify available speeds
     - The location of project specific backhaul/backbone access points
     - PTP microwave paths between towers within the project area (if applicable)
- Proposed or Upgraded Network Infrastructure (project specific) with the following layers: 
     - Proposed coverage for the communities proposed in the project; identify available speeds
     - Locations (colour differentiated) of new and upgraded towers, PoPs, fibre, PTP microwave links, and COs
     - New PTP microwave paths (colour differentiated) between towers (required for fixed wireless projects
2. There isn't really any guidance that can be given to standardize the layers to overcome pain points of data team.
3. Data team will find a way to work with the maps they get. Ideally, they want to combine all the existing data. Maybe hire co-op students to do this over the next 2 years.
- The SoW information that may be in the database would be good to mine
4. How data team will support review & assessment is to be determined. We can help facilitate this.
5. Zoey & I need to contact Justin for screening checklist to determine required functionality of application portal so data team can support screening.
6. There's a clear need to meet with the wider team and executives to discuss what everyone wants to see from the applications and the effort needed to get this information from what sources: application form, templates, maps.

**Comment by elliottSlee** [comment]
![image.png](https://images.zenhubusercontent.com/61ae5dab07758299775d9d78/edb13f66-4927-4f2a-aa15-c6b5ea4d34bb)
User Journey (on [Miro](https://miro.com/app/board/uXjVORZW4n4=/?moveToWidget=3458764531182709992&cot=14)
