### ISSUE TITLE
Milestone report - Delete

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#2009]
As an analyst
I want to be able to delete a milestone row
So that I can correct for my mistakes

# Acceptance Criteria:
[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?type=design&node-id=12418-21645&mode=design&t=bgdLnqaU8Hg6gMyA-4)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdEVTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--de301cddd38094d272e3a3946f74f073aca555ba/image.png)

- [x] When user clicks on the red x on the view page for the claim, user sees Modal asking for confirmation
- [x] When user clicks 'Yes Delete' then modal disappears and the row with the claim is deleted (soft delete in backend)
- [x] All data that were imported from the Excel file to the database are archived
- [x] When user clicks 'No Keep' then the modal disappears and the row with the milestone report stays the same and data remains in database

**Comment by MarsRomer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2009?planning-poker) with Zenhub @VB-at-Bis
