### ISSUE TITLE
Milestone report - Excel Validation

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#2014]
As an analyst
I want to see feedback when there is something wrong with the file I am uploading
So that I can correct my mistake and upload again

# Acceptance Criteria:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcTBGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f050c5932c73e85b43185925f76e1bae255d6b9c/image.png)

- [x] Check CCBC # matches
- [x] Check for existence of tabs as expected
- [x] If validation fails then provide feedback (similar to SOW validation)
- [ ] <S>Errors persist onto read-only view</S>

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2014?planning-poker) with Zenhub @marcellmueller @rafasdc @VB-at-Bis
