### ISSUE TITLE
Milestone report - Import data from Excel file

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#2015]
As an analyst
I want the milestone report data from the excel to be imported into the database
So that I don't have to spend valuable time typing it in

[Excel file with fields highlighted yellow for import](https://bcgov.sharepoint.com/:x:/r/teams/04708-ScrumTeam/Shared%20Documents/Scrum%20Team/UBF-AA-00000-Milestone-Report%20-%20fields%20for%20import%20highlighted.xlsx?d=wd1c31d50d34548e58da32f672be8f0bb&csf=1&web=1&e=93iQN8)

# Acceptance Criteria:

- [x] Excel file is imported and ingested into the database
- [x] When excel file is uploaded and validation is successful, then the Save button becomes the 'Save and Import data' button 
- [x] If the excel file is subsequently removed, the Save and Import Data button becomes the 'Save' button again
- [x] When the 'Import and Save' button is clicked, it imports data from the excel file (spinner and success toast are in another ticket)

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2015?planning-poker) with Zenhub @marcellmueller @rafasdc @VB-at-Bis

**Comment by MarsRomer** [comment]
Needs Refinement: Needs link to excel file with highlighted fields

**Comment by MarsRomer** [comment]
I just had that issue like before with other report uploads where it deleted the report right after uploading it
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ2ZIIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c76c09105fb4fdb6c4dd86adf8872b0ed2a27ceb/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ2pIIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--75fb8443e648eb5b0154b063f02e6506ade26642/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ25IIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1a829d89e8cd48f81af3c1b44ac214dc32546e9f/image.png)
