### ISSUE TITLE
Milestone report - View

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#2016]
As an analyst
I want to see the read-only version of the milestone reports that were submitted
So that I can view the claims submitted

**Description**
This ticket is for the user to see the list of claim and be able to download, and edit 

# Acceptance Criteria:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaDV4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--67d5d43c75c3856c64b0e4251a5c263e70ac0ad8/image.png)

[**Wireframe**](https://www.figma.com/file/nhOquOVmWD1P3BxEY0KIh5/CCBC-Intake?type=design&node-id=12418-21645&mode=design&t=bgdLnqaU8Hg6gMyA-4)
- [x] After pressing save on the form, this view slides in and the form slides out (same animation as announcements & the funding agreement forms)
- [x] Ordered by due date, newest on top oldest on bottom
- [x] Q (quarter) is same function as done for the community progress reports, derived from due date on the form not date received
- [x] Overall progress is from cell with the same name in the Excel file
- [x] Click on "Milestone Report" link in the view begins the download of the original file
- [ ] When user clicks the edit on the view page - the add form opens with form data
Progress bar is [MUI progress bar - linear with label](https://mui.com/material-ui/react-progress/#linear-with-label) with custom colours: 1A5A96 for bar and c3d0dc for background
- Does not include metabase report link - will be separate ticket

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2016?planning-poker) with Zenhub @AntBush @marcellmueller @rafasdc

**Comment by marcellmueller** [comment]
Adding blocked label, this needs the excel import ticket completed first.

**Comment by marcellmueller** [comment]
@elliottSlee I'm not using the Mui progress bar since it is way overkill for our needs and very fiddly and am making one from scratch since it's fairly simple. I think it's fair to suggest libraries to use in tickets but not require them as acceptance criteria.

**Comment by MarsRomer** [comment]
@marcellmueller When I try to download the milestone report from the read only view by clicking on 'Milestone Report', it ends up downloading a file without any extention to it.  But when I click edit and then download the file, it does download it properly. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdlBHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1532b525883dad462518f865ead0da45d04528ed/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdkxHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cf9f1b2b092514f8331b5f3a3a4eaa2267ab6acc/image.png)
