### ISSUE TITLE
Applicants can create multiple applications

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#220]
Currently, applicants can only create one application per user.
This ticket is to add the ability for applicants to have multiple applications.

As an Applicant
I want to create multiple applications
So that I can apply for many different projects on behalf of my company

## Acceptance criteria
- [x] Given I'm an Applicant logged in the system
When I click on [New Application] 
Then a new application is inserted into the database

**Tasks**
- [x] Database to hold more than one application by user
- [x] Routing to access the existing application
- [ ] Database testing
- [x] Create Dashboard #31

![image.png](https://images.zenhubusercontent.com/61e8875b1de5eff8f072cd04/87e83185-3b0f-4535-8ee1-a61c050f1905)

**Comment by MarsRomer** [comment]
Looks good, but the applications in the list aren't getting ordered by last edited.

**Comment by eazeredo** [comment]
The application order will be implemented in the card #31.
