### ISSUE TITLE
Add link to Metabase - Milestones

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2268]
As an analyst 
I want a link to where the Milestone dashboard is in Metabase
So that I can easily see relevant Milestone data

**Description:**
This ticket is to add a metabase link for the Milestone dashboard in Metabase - filtered by the appropriate application number

# Acceptance Criteria:
- [ ] Metabase link is implemented as per design below
- [ ] link for test envrionment:   [needs to be created]
- [ ] Link for prod env: [needs to be created]

[wireframe 1]

- [ ] Acceptance Criteria 

[wireframe 2]

- [ ] Acceptance Criteria

**Comment by MarsRomer** [comment]
@AayushAnand007 would you be able to add screen design to this ticket please?

**Comment by MarsRomer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CCBC---Delivery-Board-61c0c1204c8bcb001491c5f3/issues/bcgov/CONN-CCBC-portal/2268?planning-poker) with Zenhub @AntBush @rafasdc

**Comment by elliottSlee** [comment]
Links should be to dashboards which can be edited more easily than questions and can include a filter in the url, so clicking the link opens the dashboard filtered to that specific application.
