### ISSUE TITLE
Truncate Test data - Claims, CBC, Milestone

### ISSUE THREAD

**Issue by MarsRomer** [bcgov/CONN-CCBC-portal#2452]
Delete Claims data in TEST environment to prevent erroneous bug for previously archived records.

- [x] All claims data is deleted from the TEST database
- [x] All CBC data is deleted from the TEST database
- [x] All Milestones data is deleted from the TEST database
