### ISSUE TITLE
Assessments

### ISSUE THREAD

**Issue by elliottSlee** [bcgov/CONN-CCBC-portal#813]
```[tasklist]
# To do

- [ ] https://github.com/bcgov/CONN-CCBC-portal/issues/824
- [ ] https://github.com/bcgov/CONN-CCBC-portal/issues/848
- [ ] https://github.com/bcgov/CONN-CCBC-portal/issues/854
- [ ] https://github.com/bcgov/CONN-CCBC-portal/issues/855
- [ ] https://github.com/bcgov/CONN-CCBC-portal/issues/856
- [ ] https://github.com/bcgov/CONN-CCBC-portal/issues/804
```
